### ISSUE TITLE
OS-Climate - Establish the base software versions and tools for Stable instance cluster

### ISSUE THREAD

**Issue by redmikhail** [os-climate/os_c_data_commons#98] opened 2021-10-31 20:38 UTC
As OS-Climate environment system administrator I need an environment where I can test changes to the configuration and new versions of the applications without interrupting the work of data scientists. 

Proposal: 

Provision new OpenShift Cluster for OS-Climate project that will become production environment while keeping existing cluster with scaled down capacity for testing of new frameworks, components and configuration changes. 

Some of the proposed requirements:

* Should include separate infrastructure nodes to host monitoring/alerting, authentication workload
* OCP cluster needs to be provisioned in availability zones that provide GPU enabled EC2 instances (p3 instances)
* Nodes hosting jupyter notebooks should have taint to prevent any other workload to be scheduled to these nodes. Notebooks that require GPU resources will need to have toleration for gpu-enabled taints

**Comment by erikerlandson** [comment] 2021-11-19 18:46
cc @MichaelTiemannOSC @caldeirav

**Comment by durandom** [comment] 2021-12-01 17:10
what's the actual purpose here? from what I read we want a test env and declare the existing one stable?

**Comment by redmikhail** [comment] 2022-02-08 21:45
@durandom We want to have test/staging environment and stable/production environment for data scientists. New cluster will become this stable/production and existing cluster will become dev/staging .We probably will need to be re-built dev cluster eventually to reflect any changes in configuration and processes that have been used for provisioning of production environment

**Comment by caldeirav** [comment] 2022-02-09 01:44
@redmikhail I would actually recommend having two new clusters for DEV and PROD, and leave the existing MVP cluster running until we confirm that the new clusters work (starting with DEV), and retire it once confirmed. The reason is we want to have a clean transition to a new environment (with new address) including starting with clean storage volumes as well. This was discussed in our OS-C call yesterday and would make it easier to manage the change without impacting developers who are still on the existing cluster.

**Comment by redmikhail** [comment] 2022-02-11 00:48
@caldeirav Sorry I was under impression that we want to re-use existing cluster as dev , will add it to the tasks

**Comment by caldeirav** [comment] 2022-03-07 13:31
@redmikhail we would like to move forward with the creation of the production cluster now, before upgrading the Trino component on DEV (i.e. initially the two clusters will be in sync, then we will start working a validating changes in Dev before promoting to Prod). Do we have the required resources to create Prod? Let us know if any dependency please.

**Comment by eoriorda** [comment] 2022-04-25 14:32
Calculate quota increase and look at needs .  Airbus will decide to move based on capacity and requirements and access control. Aribus are still looking at the components and how they are deployed.  Internal work right now , not ready to run models. When they are ready to run multiple models they will need to move stable.  Decision on the "tobe " stable environment are still being made. Is it exlusive use for Airbus or is it shared.   Target is to create stable environment for Datacommons. Airibus usecase for stable environment to be determined Mikhails update

**Comment by eoriorda** [comment] 2022-07-18 14:35
Discuss with Heather how to transition this to LF team. Eileen to discuss with Heather.

**Comment by HeatherAck** [comment] 2022-07-18 18:29
Hi @eoriorda, we should include @rynofinn and @MightyNerdEric in the planning.  If Red Hat team can provide documentation on how the environment is set up, we can determine what knowledge transfer is needed to support transition

**Comment by eoriorda** [comment] 2022-07-25 17:05
@HeatherAck Develop a plan for the stable instance environment.
When will Airbus be fully operational and PRR would be the next up to migrate to the stable instance.

**Comment by HeatherAck** [comment] 2022-08-23 17:29
@HeatherAck to follow up with Matthieu, dependent on superset and tool versions

**Comment by HeatherAck** [comment] 2022-09-13 17:34
Task on hold until we have stable superset/tool versions; need final snapshot from Airbus as well - next step create plan and checklist along with criteria. Heather to schedule mtg with @caldeirav , @MichaelTiemannOSC , @redmikhail and @sostrades-matthieu-meaux

**Comment by HeatherAck** [comment] 2022-09-27 00:38
CL2 will serve as baseline for stable cluster; but timing to do so still too early (need libraries to be included in notebook (pre-reqs for pachyderm), need info removed (old version of python), need open metadata issues resolved, Trino upgrades, etc.). @HeatherAck to create pre-req checklist for stable cluster

**Comment by HeatherAck** [comment] 2022-10-04 01:00
@HeatherAck to work with @erikerlandson to finalize list

**Comment by HeatherAck** [comment] 2022-11-14 18:33
@HeatherAck to follow up with @erikerlandson on versions, etc

**Comment by HeatherAck** [comment] 2022-11-17 00:29
see also https://github.com/os-climate/os_c_data_commons/issues/234

**Comment by HeatherAck** [comment] 2023-09-18 16:07
closing dup of 234

**Closed by HeatherAck** 2023-09-18 16:07 UTC
